# trigger:
# - master

# steps: 
# - create an VHD in Packer to normal storage account
# - copy from Packer storage account to classic storage account using AzCopy
# - generate SAS link from azure CLI
# - POST a new SKU to azure marketplace

phases:
- phase: build_vhd
  queue: Hosted Linux Preview
  steps:
  - script: make init-packer && make build-packer
    displayName: Building VHD
